### ISSUE TITLE
Create Web GUI For Analyzing annotated Projects

### ISSUE THREAD

**Issue by Theophilusbenson** [eBPFDevSecTools/ebpf-projects-annotations#3]
GUI should allow users to:
(1) search the annotated projects for functions/components of interest.
(2) click on an interesting component to understand its properties.
(3) it would be cool if users can also select 2-4 components for side-by-side comparison. Similar to what Dell/Apple website allows you to compare hardware specifications.

**Comment by sdsen** [comment]
We need to investigate Kibana dashboard as an alternative for this as well.
