### ISSUE TITLE
Validate comment json as part of CI/CD 

### ISSUE THREAD

**Issue by palanik1** [eBPFDevSecTools/ebpf-projects-annotations#33]
Currently, human annotations are entered by editing the commented stub inline, potentially resulting in  invalid json input. 
Expected Behaviour: When a user raises a PR with human annotations, the CI/CD process should extract comment and check if json is valid.

**Comment by dushyantbehl** [comment]
We can either provide a test script which human comment writer should be able to run on the folder they commented and check if the generated comment is a valid json and has all fields and functions commented and set.

At minimum a commentor should attach the output of the test script in the commit message or the PR (whatever is the better practice) or the system (CI/CD) be able to run this test script on the PR and provide info if test case is succeeding or failing.

**Comment by sdsen** [comment]
Will get addressed by https://github.com/eBPFDevSecTools/annotations-search-ui/issues/7. Closing.
