### ISSUE TITLE
Create Human comments for netobserv project.

### ISSUE THREAD

**Issue by sdsen** [eBPFDevSecTools/ebpf-projects-annotations#36]
Source code is here: https://github.com/eBPFDevSecTools/ebpf-projects-annotations/tree/master/examples/netobserv-bpf-main

**Comment by dushyantbehl** [comment]
@sdsen the path seems to be incorrect, can you check

**Comment by sdsen** [comment]
Right .. @palanik1 has a new protocol.. he wants all to follow for contributing human comments. @palanik1 can you point the steps to @dushyantbehl

**Comment by palanik1** [comment]
@dushyantbehl this is done? can we close?

**Comment by dushyantbehl** [comment]
@palanik1 it was merged earlier today https://github.com/eBPFDevSecTools/ebpf-projects-annotations/pull/49
