### ISSUE TITLE
Create a search backend to query function descriptions based on search parameters.

### ISSUE THREAD

**Issue by sdsen** [eBPFDevSecTools/ebpf-projects-annotations#4]
This issue is regarding setting up Elastic, kibana and any other tools needd for the purpose of searching the annotation.

**Comment by sdsen** [comment]
@aashu2303 @Pymamid @bugAssassin007 can you write a short readme with relevant links etc. on how you got this step and push a PR ?

**Comment by bugAssassin007** [comment]
> @aashu2303 @Pymamid @bugAssassin007 can you write a short readme with relevant links etc. on how you got this step and push a PR ?

Opened a PR for this named ELASTIC_KIBANA_SETUP.md

**Comment by palanik1** [comment]
Basic set up is done.
