### ISSUE TITLE
Generated human comments stub missing sub fields.

### ISSUE THREAD

**Issue by dushyantbehl** [eBPFDevSecTools/ebpf-projects-annotations#41]
**Is your feature request related to a problem? Please describe.**

When human comments stub is generated it looks like this,

```
  "humanFuncDescription": [
    {}
  ],
  "AI_func_description": [
    {
      "description": "",
      "author": "",
      "authorEmail": "",
      "date": "",
      "invocationParameters": ""
    }
```

The `description`, `author`, `authorEmail` and `date` are missing from `humanFuncDescription` and should be added by the stub generator.

At the same time maybe `AI_Func_description` doesnt need `author` and `authorEmail` unless they mean the id of algorithm generating the comments.

**Describe the solution you'd like**

```
  "humanFuncDescription": [
    {
      "description": "",
      "author": "",
      "authorEmail": "",
      "date": "",
    }
  ],
  "AI_func_description": [
    {
      "description": "",
      "date": "",
      "invocationParameters": ""
    }
```

**Additional context**

This was taken from stub generated for netobserv code [here](https://github.com/eBPFDevSecTools/ebpf-projects-annotations/tree/master/projects/netobserv-bpf-main/human_annotated)

**Comment by palanik1** [comment]
@dushyantbehl can you pull in the latest changes

**Comment by palanik1** [comment]
Let us know if this fixes..or you had anything else in mind.

**Comment by dushyantbehl** [comment]
lgtm
