### ISSUE TITLE
Test script to check validity of human comment json

### ISSUE THREAD

**Issue by dushyantbehl** [eBPFDevSecTools/ebpf-projects-annotations#48]
**Is your feature request related to a problem? Please describe.**
Provide a test script which human comment writer should be able to run on the folder they commented and check if the generated comment is a valid json and has all fields and functions commented and set.

**Describe the solution you'd like**
At minimum a commentor should attach the output of the test script in the commit message or the PR (whatever is the better practice) or the system be able to run this test script on the PR and provide info if test case is succeeding or failing.

**Additional context**
We won't need self check as done for https://github.com/eBPFDevSecTools/ebpf-projects-annotations/issues/42

**Comment by sdsen** [comment]
@dushyantbehl is this a duplicate of #33 ? If so can you put your thoughts on that one ?

**Comment by dushyantbehl** [comment]
Closing as duplicate of #33
