### ISSUE TITLE
Add README in project folders as part of workflow script

### ISSUE THREAD

**Issue by palanik1** [eBPFDevSecTools/ebpf-projects-annotations#68]

**Comment by sdsen** [comment]
@palanik1 can you also add the disclaimer that while we have ensured atleast one pair of human eyes have reviewed the comments, we do not take any responsibility for their accuracy.

**Comment by palanik1** [comment]
@sdsen I think we should have a use "as-is /maintainers take no responsibility" clause at the top level of the project.

**Comment by palanik1** [comment]
Closing as done.

**Comment by sdsen** [comment]
> @sdsen I think we should have a use "as-is /maintainers take no responsibility" clause at the top level of the project.

@palanik1 lets have an issues to track this ?
