### ISSUE TITLE
Create annotation search capability using elastic search

### ISSUE THREAD

**Issue by sdsen** [eBPFDevSecTools/ebpf-projects-annotations#82]
We need search capabilities which create union/intersection/negation etc. of specific fields in annotation JSON.

**Comment by sdsen** [comment]
Example queries:
1. List/count all functions which use a user-input bpf_helper
2. List/count all maps used in a user-input repository
3. List/count all functions which read from a user-input map in a repository
4. List/count all functions which write to a user-input map in a repository
5. List/count the function call graph for a user-input function in a repository
6. List/count all functions which have a user-input  call_depth in a repository
7. List/count all functions which have a user_input is_root value
8. List/count all functions with non-empty value for a user-input field

**Comment by sdsen** [comment]
- [ ] 8. For a input function find all maps which are only read (and not written) across its FCG.
- [ ] 9.  For a input function find all maps which are only written (and not read) across its FCG. 
- [ ] 10.  For a input function find all maps which are read as well as written across its FCG.
- [ ] 11. For a given FCG, for all maps in that FCG, **(Identify producer-consumer relation among functions.)**
- - [ ] a. find functions which write to a map, and any of its successor function which reads the same map.
- - [ ] b. find functions which read a map, and any of its successor function which writes the same map.
- [ ] 12. Create a consolidated explainability for a function, by identifying for a user input function's FCG:
- - [ ]  a. All compatible hookpoints. (this will be a intersection of compatible hook-points for all functions).
- - [ ] b. All bpf_helpers called through FCG (function call graph).
- - [ ] c. All human extracted comments. (please think of a good data-structure, which encompasses comments (human, AI, developer) as well as  FCG.

**Comment by palanik1** [comment]
Added an additional query to try out @Pymamid @bugAssassin007 @aashu2303

**Comment by palanik1** [comment]
@Pymamid @bugAssassin007 @aashu2303 This is done? We can close?

**Comment by aashu2303** [comment]
Yes, this is done. Closing this issue
