### ISSUE TITLE
Error in elastic_loader.py line 61 and 62

### ISSUE THREAD

**Issue by aashu2303** [eBPFDevSecTools/ebpf-projects-annotations#89]
'index_name' should be 'index' in the above lines

**Comment by palanik1** [comment]
can you try now..

**Comment by aashu2303** [comment]
yes sir, that's working. In line 112, the argument to the function should be changed to args.index_name

**Comment by palanik1** [comment]
Right...I pushed in the change now.Please take a look and let me know if this works.

**Comment by aashu2303** [comment]
Working. Closing the issue
